# Generated by Django 2.1.5 on 2022-01-22 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='count_user',
            name='loginAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 12, 34, 2, 990808)),
        ),
    ]
