# Generated by Django 2.1.5 on 2022-01-22 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_count_user_loginat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_user',
            name='loginAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 19, 43, 55, 337406)),
        ),
    ]
