# Generated by Django 2.1.5 on 2022-01-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20220122_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_user',
            name='loginAt',
            field=models.CharField(max_length=5000),
        ),
    ]
