# Generated by Django 2.1.5 on 2022-01-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20220124_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
