# Generated by Django 2.1.5 on 2022-01-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20220125_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
